### ISSUE TITLE
'String' is a special class name

### ISSUE THREAD

**Issue by MatrixCrawler** [hardwiregaming/ts3-php#3]
When trying to run my script with this dependency i get this:

PHP Fatal error:  Cannot use TeamSpeak3\Helper\String as String because 'String' is a special class name in vendor\hardwiregaming\ts3-php\TeamSpeak3\TeamSpeak3.php on line 38

This problem might be related to PHP7

**Comment by arcdigital** [comment]
I think you're right, we can look into refactoring this.
